# Generated by Django 4.0.1 on 2022-10-25 09:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_remove_post_author_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rating_user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
